version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./config/nginx:/etc/nginx/conf.d
  api:
    container_name: api
    image: tutorial:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DJANGO_SETTINGS_MODULE: "tutorial.settings.docker"
    volumes:
      - .:/app
    expose:
      - "8000"
  db:
    container_name: db
    image: postgres
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: "!dlatl00"