version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - wsgi 
      - asgi
    ports:
      - "8888:8888"
      - "8889:8889"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    networks:
      tutorial-net:
        ipv4_address: 172.18.0.11
  wsgi:
    container_name: wsgi
    image: tutorial:latest
    restart: always
    depends_on:
      database:
        condition: service_healthy
    environment:
      DJANGO_SETTINGS_MODULE: "tutorial.settings.docker"
    expose:
      - "8888"
    ports:
      - "9888:8888"
    networks:
      - tutorial-net
  asgi:
    container_name: asgi
    image: tutorial:latest
    restart: always
    depends_on:
      database:
        condition: service_healthy
    environment:
      DJANGO_SETTINGS_MODULE: "tutorial.settings.docker"
    expose:
      - "8889"
    ports:
      - "9889:8889"
    command:
      - "/bin/sh"
      - "-c"
      - "python manage.py migrate ; gunicorn tutorial.asgi:application -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8889"
    networks:
      - tutorial-net
  database:
    container_name: database
    image: postgres
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: "!dlatl00"
    ports:
      - "5432:5432"
    networks:
      - tutorial-net

networks:
  tutorial-net:
    external:
      name: tutorial
